version: "3.8"

services:
  client:
    image: galaxy-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server
    networks:
      - galaxy-network

  server:
    image: galaxy-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/galaxy?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

    depends_on:
      - db
    networks:
      - galaxy-network

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=galaxy
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - galaxy-network

networks:
  galaxy-network:
    driver: bridge

volumes:
  mysql-data:
